### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by herpaderpaldent**
* made by busterguy
* i solely formatted it correctly

### CODE REVIEW

**Comment by leonjza** [comment]
Could someone that speaks Russian natively help review this please?

**Comment by ASTairov** [comment]
already doing it, the translation is not bad, there are nuances, for example the text of the translation can be longer than the original and not be placed in the field selected for it ... I correct this

**Comment by leonjza** [comment]
Thanks @ASTairov !

**Comment by ASTairov** [comment]
[seat.txt](https://github.com/eveseat/web/files/2382234/seat.txt)

**Comment by herpaderpaldent** [comment]
Cant you add your changes to this PR?

**Comment by warlof** [comment]
Has been replaced by original author pull request eveseat/web#219.

**Pull request closed without merging**
