### PR TITLE
add LP data to character page

### PR DESCRIPTION
**Pull request by recursivetree**
This pr adds a UI to view character lp data.

There is a pr in the eveapi package that needs to be merged first: https://github.com/eveseat/eveapi/pull/330, it contains the models and code to fetch lp. 

Bildschirmfoto 2022-07-04 um 14 26 54

### CODE REVIEW

**Comment by recursivetree** [comment]
I'll leave it as draft until the eveapi pr is merged

**Comment by mike0891** [comment]
Is it possible to not preselect the character but use the search box, same as the other windows like assets, killmails, wallet.

So that all of the user's LP can be seen in one location.

**Comment by warlof** [comment]
Cool, thanks for the addition.
May need adaptation at Data table class level depending on modeling changes from the job PR but not a big one.

I saw you hardcoded Forge région for LP store link. Can't we rather use the instance setup région ?

**Comment by recursivetree** [comment]
I can't find out how to use the new pivot-based model in a datatable

**Comment by warlof** [comment]
tried to give you as much hint as possible on your data source PR :)

**Pull request merged**
