### PR TITLE
Adding the beginning pieces of the Corporation Wallet Ledger options.

### PR DESCRIPTION
**Pull request by dysath**
Includes "Wallet Divisions", "Bounty Prizes By Month" and "Planetary Interaction Taxes"

### CODE REVIEW

**Comment by dysath** [comment]
Requires pull for services as well.  Submitting shortly.

**Comment by leonjza** [comment]
Thanks for your contribution! :tada: 

I had a quick read through the changes in this PR and have the following list of things that would need looking at.

- You need to remove the strings from the languages other than English, unless you can provide the proper translation.
- Remove the `.swp` files.
- Remove `src/resources/views/corporation/ledger/test.php`
- Remove `src/resources/views/corporation/ledger/target.sql`
- You have loops that do `@for ($i = 0; $i < count($pidates); $i++)` and end with `@if ((($i + 1) % 4) == 0)` that should rather be changed to being chunked with `array_chunk()` or using the `chunk()` method on a returned collection.

**Comment by warlof** [comment]
'wallet_journal' exists on current branch
'wallet_transactions' exists on current branch
'ledger'                       => 'Bilan' for the french localised file
'bountyprizesbymonth'          => 'Primes par mois',
'bountyprizetotal'             => 'Primes total',
'planetaryinteraction' exists on current branch (labelled 'pi')
'pitotals'                     => 'Total taxes Infra. Planétaire' for the french localised file

**Comment by leonjza** [comment]
> 'wallet_journal' exists on current branch
> 'wallet_transactions' exists on current branch
> 'ledger' => 'Bilan' for the french localised file

For context, I think these are the French versions of the language strings you are trying to add.

**Comment by dysath** [comment]
Excellent.  I will go through tonight and make the changes (I'll try to
figure out the chunk() option) listed along with correcting the
Documentation blocks that I shamefully copy/pasted and did not adjust
accordingly.

I will also add the French translations in.  Thanks for working with me on
this.

On Mon, Apr 4, 2016 at 3:14 AM, Leon Jacobs <notifications@github.com>
wrote:

> 'wallet_journal' exists on current branch
> 'wallet_transactions' exists on current branch
> 'ledger' => 'Bilan' for the french localised file
>
> For context, I think these are the French versions of the language strings
> you are trying to add.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eveseat/web/pull/23#issuecomment-205185052>
>



-- 
Ed Stafford

**Comment by dysath** [comment]
An interesting case:

So, 'pi' exists in both en and fr, but the french is spelled out where the
english is simply 'PI'.

en:
    'pi'                           => 'PI',

fr:
    'pi'                           => 'Infra. PlanÃ©taire',

Should the english be "fixed"?

On Mon, Apr 4, 2016 at 8:44 AM, Ed Stafford <ed.stafford@gmail.com> wrote:

> Excellent.  I will go through tonight and make the changes (I'll try to
> figure out the chunk() option) listed along with correcting the
> Documentation blocks that I shamefully copy/pasted and did not adjust
> accordingly.
>
> I will also add the French translations in.  Thanks for working with me on
> this.
>
> On Mon, Apr 4, 2016 at 3:14 AM, Leon Jacobs <notifications@github.com>
> wrote:
>
>> 'wallet_journal' exists on current branch
>> 'wallet_transactions' exists on current branch
>> 'ledger' => 'Bilan' for the french localised file
>>
>> For context, I think these are the French versions of the language
>> strings you are trying to add.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/eveseat/web/pull/23#issuecomment-205185052>
>>
>
>
>
> --
> Ed Stafford
>



-- 
Ed Stafford

**Comment by leonjza** [comment]
> Should the english be "fixed"?

Nah. The full wording takes up a crapton of space. If you dont know what PI is... well...

**Comment by dysath** [comment]
Requisite changes have been committed.  Continue please.

**Pull request merged**
