### PR TITLE
Added a 'Corporation Characters' Affilation

### PR DESCRIPTION
**Pull request by SauerRam**
Added a 'Corporation Characters' Affilation to ACL which provides access to all Characters in the affilated Corporations within the Role. Works with multiple Corporations too.

### CODE REVIEW

**Comment by shadowcodex** [comment]
@leonjza sorry, check this?

**Comment by leonjza** [comment]
@shadowcodex As soon as I have a gap I'll give it a test!

**Comment by SauerRam** [comment]
anything new about the PR integration?

**Comment by leonjza** [comment]
Testing this, listing the characters I can see with the, it seems like I can see all characters on SeAT. I have setup the affiliation as follows, allowing me to see characters in other corporations still:

screen shot 2017-08-12 at 11 23 24 am


What is the intended configuration for this PR to work @SauerRam ?

**Comment by leonjza** [comment]
Ping @SauerRam

**Pull request closed without merging**
