### PR TITLE
Added a "Corporation Characters" Option to Acl

### PR DESCRIPTION
**Pull request by SauerRam**

### CODE REVIEW

**Comment by shadowcodex** [comment]
can we get this tested and merged?

**Comment by leonjza** [comment]
Yeah this looks ok. Just tested it quickly though. Just want to make sure there are not cases introduced here where privileges get confused. Soon™

**Comment by leonjza** [comment]
@SauerRam  how is this supposed to work? There is a new field _Corp Characters_ under the _Available Characters_ section. So if I create a role with say the **Character.list** permission and the **Corporation Characters** affiliation, I can list every character in the system.

I added an extra corporation affiliation to test as well, but then can still list every character in the system.

**Comment by SauerRam** [comment]
guess i found my mistake, will rework this soon

**Comment by shadowcodex** [comment]
@SauerRam how soon is soon? :)

**Comment by SauerRam** [comment]
https://github.com/eveseat/web/pull/76

**Comment by shadowcodex** [comment]
@leonjza check?

**Pull request closed without merging**
