### PR TITLE
add language Chinese

### PR DESCRIPTION
**Pull request by violarulan**
Add Chinese support

### CODE REVIEW

**Comment by leonjza** [comment]
Awesome! 🎉  
I obviously have no way to validate the strings themselves, but I noticed there are some that are still English. Is this intended @violarulan ?

**Comment by violarulan** [comment]
@leonjza My mistake. I corrected them and commited :)

**Comment by warlof** [comment]
Woooow, sweet Chiness characters everywhere :o
Nice work :)

**Comment by leonjza** [comment]
Thanks! This will be available in the next release shortly :)

**Pull request merged**
