### PR TITLE
Add tab for users with `character.list` permission

### PR DESCRIPTION
**Pull request by herpaderpaldent**
* This regards  feature request https://github.com/eveseat/seat/issues/359
* with SeAT Group Tab one can receive another table with only
 character belonging to the users group.

image
image

### CODE REVIEW

**Comment by leonjza** [comment]
Nice one thanks!

**Comment by kwazulueve** [comment]
Thanks for implementing this feature :)

However currently I only see my logged in character in that overview, while I have 21 characters in my personal user group.

image

image

**Comment by herpaderpaldent** [comment]
@kwazulueve i created 2 pull request that should really do the deal. Sorry i made a misstake during development.

**Comment by kwazulueve** [comment]
Awesome, thank you!

**Pull request merged**
