### PR TITLE
Fix issue eveseat/issues#38

### PR DESCRIPTION
**Pull request by warlof**
This commit fix the wishlist #38 started here https://github.com/eveseat/seat/issues/38

### CODE REVIEW

**Comment by leonjza** [comment]
Dont you think we should refactor this to have something like?

```html
<a href="@if (auth()->user()->has('queue_manager')) {{ route() }} @else #"></a>
```

**Comment by warlof** [comment]
I found this more readable, but if you prefer to do like this, i'll fix it this evening.

**Comment by leonjza** [comment]
Not not very obvious that only the `href` tags are modified like this.

**Comment by warlof** [comment]
done with a ternar =)

**Comment by leonjza** [comment]
Muuuuuch nicer :D

**Pull request merged**
