### PR TITLE
Rename EveonlineProvider.php to EveOnlineProvider.php

### PR DESCRIPTION
**Pull request by dnwright**
SSO fails to work on linux with the filename having a lower case O for Online.

### CODE REVIEW

**Comment by warlof** [comment]
Which distribution are you on ?

**Comment by dnwright** [comment]
Centos 7 64bit

**Comment by leonjza** [comment]
Thanks for your contribution! :+1: Ill test this asap.
If anything, this makes the app even more PSR4 complaint :)

**Comment by leonjza** [comment]
Thanks for helping make SeAT more awesome!

**Pull request merged**
