### PR TITLE
Settings Page Update 6.0.x

### PR DESCRIPTION
**Pull request by Crypta-Eve**
This PR updates the SeAT Settings page to use new Tabler classes and also remove the dependency on jQuery.

image

### CODE REVIEW

**Comment by Crypta-Eve** [comment]
I'd love to have thoughts on the new layout I added here. It's called 6-6_12, based on an even left/right side and a full-width bottom section. I felt it fits here as it makes it a lot easier to work with custom links due to form widths.

The only other concern I have is regarding the table within a card... I am not sure how to make that fill the card content.

**Comment by warlof** [comment]
Hey, as of table, you can check within the character list. There is a class to add to either the body or the table (render call)

**Comment by Crypta-Eve** [comment]
Ok, this is what I get using the `card-table` class. Thoughts?
image

**Comment by warlof** [comment]
Maybe we should keep settings as clean as possible. Should we extract the custom link pane into a dedicated page ?

**Comment by recursivetree** [comment]
We could, although I don't think it really matters. On another note, I have been considering to add the option to link seat-info articles the way custom links work. Maybe we could store the links in a db table instead of a string in the settings

**Pull request closed without merging**
