### PR TITLE
Add CN translation

### PR DESCRIPTION
**Pull request by ArielHeleneto**
Add CN translation

### CODE REVIEW

**Review by warlof — COMMENTED** [review]
Hi,

Some captions use singular/plural notation and seems not beeing translated accordingly. Is that intended? (especially in the moon file)

Also, there are remaining English caption. Is it intended as well?

**Comment by ArielHeleneto** [comment]
> Hi,
> 
> Some captions use singular/plural notation and seems not beeing translated accordingly. Is that intended? (especially in the moon file)
> 
> Also, there are remaining English caption. Is it intended as well?

For the first question , of course yes. In Chinese , we don't have regular form.It is the same. I have tried in my SeAT system, it works as Chinese's minds.

second question, some of them are intended because we are still having conversations. Eve do not have Chinese official version. We do keep it as same as it performed in the game.

**Comment by ArielHeleneto** [comment]
src/resources/lang/zh-CN/seat.php and src/resources/lang/zh-CN/permissions.php are not translated yet because i don't have much time

**Comment by tehraven** [comment]
@ArielHeleneto this is a huge step forward for Chinese players using SeAT. Are you able to find another Chinese speaker who can finish up? This would be wonderful to get merged!

**Comment by warlof** [comment]
if you remove the untranslated entries, it's mergeable.
we don't need all keys to be translated - when a caption is not found in target language, the default one is selected (english)

**Comment by ArielHeleneto** [comment]
> @ArielHeleneto this is a huge step forward for Chinese players using SeAT. Are you able to find another Chinese speaker who can finish up? This would be wonderful to get merged!

emmm,i can not find another one to help me.

**Pull request merged**
