### PR TITLE
Correct form for confirmform

### PR DESCRIPTION
**Pull request by veteranmina**
Corrects form not posting action after confirming action

### CODE REVIEW

**Comment by warlof** [comment]
What's the change?

**Comment by veteranmina** [comment]
I moved the contents of <button></button> to inside the form as it does not register the action outside the form.

**Comment by veteranmina** [comment]
To be more specific, this corrects the reject button for squad candidates not functioning as intended. The confirmation form would present itself but confirming the action did not complete due to the button existing outside the form code.

**Comment by warlof** [comment]
`form` attribute is normally designed for such purpose, will need a bit extra investigation

**Comment by veteranmina** [comment]
Reverted reject.blade.php and changed seat.js to review form/attr. This brings compatibility between forms that have buttons existing inside or outside their *.blade.php forms

**Pull request merged**
